/*
  ==============================================================================
    FontManager.h
    Manrope Font Management for ToneMatch AI
  ==============================================================================
*/

#pragma once

#include <juce_gui_basics/juce_gui_basics.h>
#include "BinaryData.h"

class FontManager
{
public:
    static FontManager& getInstance()
    {
        static FontManager instance;
        return instance;
    }

    void initialise()
    {
        if (! initialised)
        {
            manropeLight     = loadFont("Manrope-Light.ttf");
            manropeRegular   = loadFont("Manrope-Regular.ttf");
            manropeMedium    = loadFont("Manrope-Medium.ttf");
            manropeSemiBold  = loadFont("Manrope-SemiBold.ttf");
            manropeBold      = loadFont("Manrope-Bold.ttf");
            manropeExtraBold = loadFont("Manrope-ExtraBold.ttf");

            initialised = true;
        }
    }

    juce::Font getLight    (float height) const { return withHeight(manropeLight,     height); }
    juce::Font getRegular  (float height) const { return withHeight(manropeRegular,   height); }
    juce::Font getMedium   (float height) const { return withHeight(manropeMedium,    height); }
    juce::Font getSemiBold (float height) const { return withHeight(manropeSemiBold,  height); }
    juce::Font getBold     (float height) const { return withHeight(manropeBold,      height); }
    juce::Font getExtraBold(float height) const { return withHeight(manropeExtraBold, height); }

private:
    FontManager() = default;

    juce::Font loadFont(const juce::String& filename)
    {
        const void* data   = nullptr;
        int         length = 0;

        // Map logical names to BinaryData symbols generated by juce_add_binary_data
        if (filename == "Manrope-Light.ttf")
        {
            data   = BinaryData::ManropeLight_ttf;
            length = BinaryData::ManropeLight_ttfSize;
        }
        else if (filename == "Manrope-Regular.ttf")
        {
            data   = BinaryData::ManropeRegular_ttf;
            length = BinaryData::ManropeRegular_ttfSize;
        }
        else if (filename == "Manrope-Medium.ttf")
        {
            data   = BinaryData::ManropeMedium_ttf;
            length = BinaryData::ManropeMedium_ttfSize;
        }
        else if (filename == "Manrope-SemiBold.ttf")
        {
            data   = BinaryData::ManropeSemiBold_ttf;
            length = BinaryData::ManropeSemiBold_ttfSize;
        }
        else if (filename == "Manrope-Bold.ttf")
        {
            data   = BinaryData::ManropeBold_ttf;
            length = BinaryData::ManropeBold_ttfSize;
        }
        else if (filename == "Manrope-ExtraBold.ttf")
        {
            data   = BinaryData::ManropeExtraBold_ttf;
            length = BinaryData::ManropeExtraBold_ttfSize;
        }

        if (data != nullptr && length > 0)
        {
            auto typeface = juce::Typeface::createSystemTypefaceFor(data, length);
            return juce::Font(typeface);
        }

        // Fallback to a generic system font if something goes wrong
        return juce::Font(juce::FontOptions(14.0f));
    }

    static juce::Font withHeight(const juce::Font& base, float height)
    {
        juce::Font f(base);
        f.setHeight(height);
        return f;
    }

    bool initialised = false;

    juce::Font manropeLight;
    juce::Font manropeRegular;
    juce::Font manropeMedium;
    juce::Font manropeSemiBold;
    juce::Font manropeBold;
    juce::Font manropeExtraBold;
};


